[workspace]
authors = ["paparon96 <aron.pap@barcelonagse.eu>"]
channels = ["conda-forge"]
name = "ml4rs"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.7,<3.14"
numpy = ">=2.3.3,<3"
matplotlib = ">=3.10.6,<4"
scikit-learn = ">=1.7.2,<2"
xgboost = ">=3.0.5,<4"
pytorch = ">=2.8.0,<3"
tqdm = ">=4.67.1,<5"
